# Generated by Django 5.1.1 on 2024-10-03 17:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_productsales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likedreview',
            unique_together={('user', 'review')},
        ),
    ]
