# Generated by Django 5.1.1 on 2024-10-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginfo',
            name='address',
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
